### ISSUE TITLE
The Paypal Module is not working on Multi Store Environment

### ISSUE THREAD

**Issue by litan1106** [PrestaShop/paypal#15]
The Paypal Module is not working on Multi Store Environment

**Comment by gaillafr** [comment]
Hi @litan1106. Could you please describe your bug?
Thank you, kind regards.

**Comment by litan1106** [comment]
I have the Prestashop 1.6.0.14 and setup as Multi Store Environment. I setup Paypal with Paypal Payments Standard and (Test)Sandbox mode.
1. Add an item to the cart on one of my multi store
2. Sign in my account, use default address, select a shipping and checkout with Paypal 
3. Pay with a sandbox account.
4. Paypal process the payment and redirect me back to my store

NOTE: It processed the payment and took my money but it didn't create the order. I still see the item on my cart. THANKS
