### ISSUE TITLE
paypal rewrite shipping address.

### ISSUE THREAD

**Issue by hiousi** [PrestaShop/paypal#16]
When payment is confirmed the module rewrites customer shipping address with Paypal account datas.
After that the merchant is unable to ship to the address that the customer has choosen on checkout.

This happens around lines 211 of file  /express_checkout/payment.php

**Comment by simondaigre** [comment]
Hi,

Same problem with this issue, plus a problem with character's accents encoding.

**Comment by hiousi** [comment]
corrected with commit 8b50bb839e8607c80031787c323b5d4dd048569a
