### ISSUE TITLE
An error occurred. Please check your credentials.

### ISSUE THREAD

**Issue by CodingPeak** [PrestaShop/paypal#78]
I followed all instructions trying to setup PayPal, but I keep getting the error "An error occurred. Please check your credentials.". What am I doing wrong? I'm using Prestashop 1.7.1.2 and PayPal v4.0.1

**Comment by blindpenguin** [comment]
I stumbled accross the same problem. In my case it was a misunderstanding in which keys to use. If you go to this site: https://developer.paypal.com/developer/applications/ 

Scroll down to "REST API apps" and click your app (or create if not existent) and there you find all your sandbox and live keys. Copy those, go to your prestashop at paypal "products" and click on change. There you can paste them in.

**Comment by CodingPeak** [comment]
Hi @blindpenguin, thanks for your answer. I debugged the error message and the reason was that curl (in PHP) had no ca certificate bundle to use. Case closed!
